/// [Triangular, pentagonal, and hexagonal](https://projecteuler.net/problem=45)
///
/// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
///
/// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
/// Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
/// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
///
/// It can be verified that T285 = P165 = H143 = 40755.
/// solve() returns next triangular number after 40755 that are also pentagonal and hexagonal
///
/// # Example
///
/// ```
/// assert_eq!(project_euler::solution::p045::solve(), 1533776805);
/// ```
pub fn solve() -> usize {
    // Number is triangular if it is hexagonal, so check if hexagonal number is also pentagonal
    for i in 144.. {
        let n = i * (2 * i - 1);

        if is_pentagonal(n) {
            return n;
        }
    }

    unreachable!()
}

fn is_pentagonal(p: usize) -> bool {
    let n = ((1.0 + 24.0 * p as f64).sqrt() + 1.0) / 6.0;
    n.fract() == 0.0
}
